### ISSUE TITLE
obsolete npm package

### ISSUE THREAD

**Issue by vdegenne** [Duske/custom-element-decorator#1]
Hello,

Could you consider removing `custom-element-decorator` from npm registry, it's 7 years old and obsolete.
Or could as well update your package to reflect the new norms.

Thanks

**Comment by Duske** [comment]
@vdegenne Thanks for the hint, I unpublished it 👍🏼  Should be processed within a few minutes

**Comment by vdegenne** [comment]
@Duske you're the man :+1: 
Do you mind if I take the name? I made a decorator which is respecting the new standards, esm friendly, typescript declarations provided, automatic naming, inject into the dom option, ...
Thanks

**Comment by Duske** [comment]
@vdegenne Sure, go for it :) Let me also put this repository to archive. If you tell me the repository, I can also provide a link to your modern version 🤓

**Comment by vdegenne** [comment]
@Duske Here's the link : https://www.npmjs.com/package/custom-element-decorator
It's funny npm doesn't reset the "Weekly Downloads" chart :sweat_smile:
